version: '3.8'

services:
 node:
   build:
     context: .
     dockerfile: Dockerfile
   volumes:
     - .:/app
   ports:
     - 3000:3000
   command: npm start

 react:
   build:
     context: ./client
     dockerfile: Dockerfile
   volumes:
     - ./client:/app
   ports:
     - 3001:3000
   command: npm start
